twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /nav2/cmd_vel
        timeout: 0.5
        priority: 10
      tracker:
        topic: /cmd_vel_tracker
        timeout: 0.5
        priority: 20
      teleop_keyboard:
        topic: /cmd_vel
        timeout: 0.5
        priority: 100
    output_topic: /merged_cmd_vel